token: "lip_GhpvtqTJFmhEWEebp6aq"    # Lichess OAuth2 Token
url: "https://lichess.org/"    # Lichess base URL.

engine:
  dir: "./"
  name: "./engines/stockfish.exe"
  protocol: "uci"
  
challenge:
  concurrency: 1
  sort_by: "best"
  accept_bot: true
  only_bot: true
  initial_time: 60
  increment: 1
  variants:
    - standard
  time_controls:
    - bullet
    - blitz
  modes:
    - rated
